[project]
name = "disqco"
version = "0.0.5"
description = "DIStributed Quantum Circuit Optimisation"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "qiskit",
    "qiskit-aer",
    "qiskit-qasm3-import",
    "networkx",
    "matplotlib",
    "pylatexenc",
    "jupyter-tikz",
    "ipykernel",
    "pytest",
    "tqdm",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"